<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Candidat;
use Carbon\Carbon;

class CandidatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $candidats = [
            [
                'nom' => 'Dupont',
                'prenom' => 'Marie',
                'email' => 'marie.dupont@email.com',
                'telephone' => '06 12 34 56 78',
                'adresse' => '123 Rue de la Paix',
                'ville' => 'Paris',
                'code_postal' => '75001',
                'pays' => 'France',
                'date_naissance' => '1985-03-15',
                'lieu_naissance' => 'Paris',
                'nationalite' => 'Française',
                'civilite' => 'Mme',
                'linkedin' => 'https://linkedin.com/in/marie-dupont',
                'site_web' => 'https://marie-dupont.dev',
                'bio' => 'Développeuse Full-Stack avec 8 ans d\'expérience dans le développement web moderne.',
                'competences' => 'PHP, Laravel, JavaScript, Vue.js, MySQL, Git, Docker',
                'experiences' => 'Lead Developer chez TechCorp (2019-2023), Senior Developer chez WebAgency (2016-2019)',
                'formation' => 'Master en Informatique - Université Paris-Sorbonne (2015)',
                'disponibilite' => 'Immédiat',
                'pretention_salaire' => 65000.00,
                'mobilite' => 'Région parisienne',
                'statut' => 'actif',
                'notes' => 'Excellente candidate, très motivée et compétente.',
                'source_recrutement' => 'LinkedIn',
            ],
            [
                'nom' => 'Martin',
                'prenom' => 'Thomas',
                'email' => 'thomas.martin@email.com',
                'telephone' => '06 98 76 54 32',
                'adresse' => '456 Avenue des Champs',
                'ville' => 'Lyon',
                'code_postal' => '69001',
                'pays' => 'France',
                'date_naissance' => '1990-07-22',
                'lieu_naissance' => 'Lyon',
                'nationalite' => 'Française',
                'civilite' => 'M',
                'linkedin' => 'https://linkedin.com/in/thomas-martin',
                'site_web' => null,
                'bio' => 'Développeur Backend spécialisé en architecture microservices.',
                'competences' => 'Java, Spring Boot, PostgreSQL, Redis, Kafka, Kubernetes',
                'experiences' => 'Senior Backend Developer chez DataTech (2020-2023), Developer chez SoftCorp (2018-2020)',
                'formation' => 'Ingénieur en Informatique - INSA Lyon (2018)',
                'disponibilite' => '1 mois',
                'pretention_salaire' => 70000.00,
                'mobilite' => 'Lyon et région',
                'statut' => 'actif',
                'notes' => 'Profil technique solide, bonne expérience en microservices.',
                'source_recrutement' => 'Indeed',
            ],
            [
                'nom' => 'Bernard',
                'prenom' => 'Sophie',
                'email' => 'sophie.bernard@email.com',
                'telephone' => '06 55 44 33 22',
                'adresse' => '789 Boulevard Central',
                'ville' => 'Marseille',
                'code_postal' => '13001',
                'pays' => 'France',
                'date_naissance' => '1988-11-08',
                'lieu_naissance' => 'Marseille',
                'nationalite' => 'Française',
                'civilite' => 'Mme',
                'linkedin' => 'https://linkedin.com/in/sophie-bernard',
                'site_web' => 'https://sophie-bernard.com',
                'bio' => 'UX/UI Designer passionnée par l\'expérience utilisateur et l\'innovation.',
                'competences' => 'Figma, Adobe Creative Suite, Sketch, InVision, Prototyping, User Research',
                'experiences' => 'Senior UX Designer chez DesignStudio (2021-2023), UX Designer chez WebDesign (2019-2021)',
                'formation' => 'Master en Design Numérique - École Supérieure d\'Art (2019)',
                'disponibilite' => 'Immédiat',
                'pretention_salaire' => 55000.00,
                'mobilite' => 'Marseille, Aix-en-Provence',
                'statut' => 'actif',
                'notes' => 'Portfolio impressionnant, très créative.',
                'source_recrutement' => 'Spontanée',
            ],
            [
                'nom' => 'Petit',
                'prenom' => 'Lucas',
                'email' => 'lucas.petit@email.com',
                'telephone' => '06 11 22 33 44',
                'adresse' => '321 Rue du Commerce',
                'ville' => 'Toulouse',
                'code_postal' => '31000',
                'pays' => 'France',
                'date_naissance' => '1992-04-12',
                'lieu_naissance' => 'Toulouse',
                'nationalite' => 'Française',
                'civilite' => 'M',
                'linkedin' => 'https://linkedin.com/in/lucas-petit',
                'site_web' => null,
                'bio' => 'Développeur Frontend avec une passion pour les interfaces utilisateur modernes.',
                'competences' => 'React, TypeScript, Next.js, Tailwind CSS, GraphQL, Jest',
                'experiences' => 'Frontend Developer chez ReactCorp (2021-2023), Junior Developer chez WebStart (2020-2021)',
                'formation' => 'Licence en Informatique - Université Paul Sabatier (2020)',
                'disponibilite' => '2 semaines',
                'pretention_salaire' => 45000.00,
                'mobilite' => 'Toulouse',
                'statut' => 'actif',
                'notes' => 'Jeune développeur prometteur, très motivé.',
                'source_recrutement' => 'LinkedIn',
            ],
            [
                'nom' => 'Robert',
                'prenom' => 'Emma',
                'email' => 'emma.robert@email.com',
                'telephone' => '06 99 88 77 66',
                'adresse' => '654 Avenue de la République',
                'ville' => 'Nantes',
                'code_postal' => '44000',
                'pays' => 'France',
                'date_naissance' => '1987-09-30',
                'lieu_naissance' => 'Nantes',
                'nationalite' => 'Française',
                'civilite' => 'Mme',
                'linkedin' => 'https://linkedin.com/in/emma-robert',
                'site_web' => 'https://emma-robert.dev',
                'bio' => 'DevOps Engineer spécialisée dans l\'automatisation et l\'infrastructure cloud.',
                'competences' => 'Docker, Kubernetes, AWS, Terraform, Jenkins, Linux, Bash',
                'experiences' => 'DevOps Engineer chez CloudTech (2020-2023), System Administrator chez ITCorp (2018-2020)',
                'formation' => 'Master en Systèmes d\'Information - Université de Nantes (2018)',
                'disponibilite' => '1 mois',
                'pretention_salaire' => 75000.00,
                'mobilite' => 'Nantes, Rennes',
                'statut' => 'actif',
                'notes' => 'Excellente compétence en DevOps, très expérimentée.',
                'source_recrutement' => 'Indeed',
            ],
            [
                'nom' => 'Durand',
                'prenom' => 'Alexandre',
                'email' => 'alexandre.durand@email.com',
                'telephone' => '06 77 66 55 44',
                'adresse' => '987 Place de la Liberté',
                'ville' => 'Bordeaux',
                'code_postal' => '33000',
                'pays' => 'France',
                'date_naissance' => '1989-12-03',
                'lieu_naissance' => 'Bordeaux',
                'nationalite' => 'Française',
                'civilite' => 'M',
                'linkedin' => 'https://linkedin.com/in/alexandre-durand',
                'site_web' => null,
                'bio' => 'Data Scientist avec expertise en machine learning et analyse prédictive.',
                'competences' => 'Python, TensorFlow, PyTorch, Pandas, NumPy, SQL, AWS',
                'experiences' => 'Senior Data Scientist chez DataLab (2021-2023), Data Analyst chez AnalyticsCorp (2019-2021)',
                'formation' => 'PhD en Intelligence Artificielle - Université de Bordeaux (2019)',
                'disponibilite' => 'Immédiat',
                'pretention_salaire' => 85000.00,
                'mobilite' => 'Bordeaux, Paris',
                'statut' => 'actif',
                'notes' => 'Profil exceptionnel, très qualifié en ML.',
                'source_recrutement' => 'LinkedIn',
            ],
            [
                'nom' => 'Moreau',
                'prenom' => 'Julie',
                'email' => 'julie.moreau@email.com',
                'telephone' => '06 33 44 55 66',
                'adresse' => '147 Rue de la Gare',
                'ville' => 'Strasbourg',
                'code_postal' => '67000',
                'pays' => 'France',
                'date_naissance' => '1991-06-18',
                'lieu_naissance' => 'Strasbourg',
                'nationalite' => 'Française',
                'civilite' => 'Mme',
                'linkedin' => 'https://linkedin.com/in/julie-moreau',
                'site_web' => 'https://julie-moreau.com',
                'bio' => 'Product Manager avec une approche centrée sur l\'utilisateur.',
                'competences' => 'Product Strategy, User Research, A/B Testing, Agile, Jira, Figma',
                'experiences' => 'Product Manager chez ProductCorp (2020-2023), Associate PM chez StartupTech (2019-2020)',
                'formation' => 'MBA - HEC Paris (2019)',
                'disponibilite' => '2 mois',
                'pretention_salaire' => 65000.00,
                'mobilite' => 'Strasbourg, Paris',
                'statut' => 'actif',
                'notes' => 'Bonne expérience produit, profil intéressant.',
                'source_recrutement' => 'Indeed',
            ],
            [
                'nom' => 'Leroy',
                'prenom' => 'Pierre',
                'email' => 'pierre.leroy@email.com',
                'telephone' => '06 88 99 00 11',
                'adresse' => '258 Boulevard des Alpes',
                'ville' => 'Grenoble',
                'code_postal' => '38000',
                'pays' => 'France',
                'date_naissance' => '1986-01-25',
                'lieu_naissance' => 'Grenoble',
                'nationalite' => 'Française',
                'civilite' => 'M',
                'linkedin' => 'https://linkedin.com/in/pierre-leroy',
                'site_web' => null,
                'bio' => 'Développeur Mobile spécialisé en applications iOS et Android.',
                'competences' => 'Swift, Kotlin, React Native, Flutter, Firebase, Git',
                'experiences' => 'Mobile Developer chez AppStudio (2021-2023), iOS Developer chez MobileCorp (2019-2021)',
                'formation' => 'Master en Développement Mobile - Université Grenoble Alpes (2019)',
                'disponibilite' => 'Immédiat',
                'pretention_salaire' => 60000.00,
                'mobilite' => 'Grenoble, Lyon',
                'statut' => 'inactif',
                'notes' => 'Bon développeur mobile, mais moins disponible.',
                'source_recrutement' => 'LinkedIn',
            ],
            [
                'nom' => 'Simon',
                'prenom' => 'Camille',
                'email' => 'camille.simon@email.com',
                'telephone' => '06 22 33 44 55',
                'adresse' => '369 Avenue de la Mer',
                'ville' => 'Nice',
                'code_postal' => '06000',
                'pays' => 'France',
                'date_naissance' => '1993-08-14',
                'lieu_naissance' => 'Nice',
                'nationalite' => 'Française',
                'civilite' => 'Mlle',
                'linkedin' => 'https://linkedin.com/in/camille-simon',
                'site_web' => 'https://camille-simon.fr',
                'bio' => 'Développeuse Full-Stack junior avec une passion pour les nouvelles technologies.',
                'competences' => 'JavaScript, React, Node.js, MongoDB, Express, Git',
                'experiences' => 'Junior Developer chez WebStart (2022-2023), Stage chez TechCorp (2022)',
                'formation' => 'Licence en Informatique - Université Côte d\'Azur (2022)',
                'disponibilite' => 'Immédiat',
                'pretention_salaire' => 35000.00,
                'mobilite' => 'Nice, Monaco',
                'statut' => 'actif',
                'notes' => 'Jeune développeuse prometteuse, très motivée.',
                'source_recrutement' => 'Spontanée',
            ],
            [
                'nom' => 'Michel',
                'prenom' => 'Antoine',
                'email' => 'antoine.michel@email.com',
                'telephone' => '06 44 55 66 77',
                'adresse' => '741 Rue du Port',
                'ville' => 'Le Havre',
                'code_postal' => '76600',
                'pays' => 'France',
                'date_naissance' => '1984-05-20',
                'lieu_naissance' => 'Le Havre',
                'nationalite' => 'Française',
                'civilite' => 'M',
                'linkedin' => 'https://linkedin.com/in/antoine-michel',
                'site_web' => null,
                'bio' => 'Développeur Senior avec expertise en architecture logicielle et performance.',
                'competences' => 'Java, Spring, Microservices, Docker, Kubernetes, PostgreSQL, Redis',
                'experiences' => 'Senior Developer chez EnterpriseCorp (2018-2023), Lead Developer chez TechStart (2015-2018)',
                'formation' => 'Ingénieur en Informatique - École Centrale Paris (2015)',
                'disponibilite' => '3 mois',
                'pretention_salaire' => 80000.00,
                'mobilite' => 'Normandie, Paris',
                'statut' => 'blacklist',
                'notes' => 'Candidat blacklisté - comportement inapproprié lors de l\'entretien.',
                'source_recrutement' => 'LinkedIn',
            ],
        ];

        foreach ($candidats as $candidat) {
            Candidat::create($candidat);
        }

        $this->command->info('Candidats créés avec succès !');
    }
}
